### ISSUE TITLE
Missing example for `query` parameter

### ISSUE THREAD

**Issue by pupitooo** [mailchimp/mailchimp-client-lib-codegen#106]
Spec: Marketing, Section: search-members

What was unclear / unexpected / confusing: 

There are missing example for `query` parameter. I do not know if there are possible to write some json for specific search, or there are no support for searching in specific parameters.

**Comment by bipol-mc** [comment]
Hey @pupitooo -

I'll look into updating the documentation for this endpoint, but I believe the `query` parameter allows you to do a match on the email for a given member, or a match on the first name or last name merge value.  If a valid email is provided, we search for that field, otherwise we will attempt to partial match the email, first name, or last name.

**Comment by bipol-mc** [comment]
Closing with #116 merged
