### ISSUE TITLE
Typescript @type definitions missing in npm libraries

### ISSUE THREAD

**Issue by ekwus** [mailchimp/mailchimp-client-lib-codegen#134]
Hi

We are using both the marketing and transactional API libraries in a Node project with Typescript. However the type definitions for each are incomplete.

For marketing we are able to provide our own override which helps but is a pain to add new functionality.

For transactional, we have not been able to override the types due to the way the initialisation uses a default function and defining it for Typescript is beyond our understanding. We are having to use this lib without type safety.

Would be great to either have the types and module definitions fully generated in the libraries or even for a sub project to be pushed to the Definitely Typed project @types

Cheers

Dave

**Comment by kstolte** [comment]
I believe this issue is related.
https://github.com/mailchimp/mailchimp-client-lib-codegen/issues/162

**Comment by rattkin** [comment]
the npm package contains problematic file types.d.ts
```
/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

declare namespace OpenAPI2 {}
```
This makes www.npmjs.com think it has type definitions, when in fact it does not. 
What is more problematic is, that it prevents barrel importing of the file.

Please remove the file.

**Comment by rattkin** [comment]
> For marketing we are able to provide our own override which helps but is a pain to add new functionality.

would you please share your own types?
I'm trying to add my own to DefinitelyTyped and would appreciate a PR

**Comment by devuxer** [comment]
The non-working TypeScript experience is a massive blocker for me. It would probably be better to have no types at all than types that don't even let you import the package in the first place.

**Comment by orta** [comment]
The bad `.d.ts` file looks like a mistake, because it used to be included correctly - https://github.com/mailchimp/mailchimp-marketing-node/blob/8a6d0aaabb46442e3c97a2679cdd5c09e7409358/types.d.ts#L5

I'm hesitant to accept the new types to DefinitelyTyped given the _intent_ was for Mailchimp to ship their own types, duplicating the types across  2 systems will make life harder for Mailchimp folks in the long run and I'd rather that not be the case. 

I would someone with commit access to offer an opinion, in the meantime I'm going to leave a note on the DT PR that I'll be leaving it for this week to give a contributor chance to comment

**Comment by xiaoyu-tamu** [comment]
will this get fixed? or this is expected behavior ??

**Comment by intellix** [comment]
@mc-hannah-morrison do you mind if I ping you into here? It looks like the type definitions exported are broken entirely as per https://github.com/mailchimp/mailchimp-client-lib-codegen/issues/134#issuecomment-858413237

**Comment by mc-hannah-morrison** [comment]
Apologies for the slow response on this. I pushed #201 to remove the bad types. 
We don't have plans to better support TypeScript in the short term
