### ISSUE TITLE
How to add metadata to a list member

### ISSUE THREAD

**Issue by jfanals** [mailchimp/mailchimp-client-lib-codegen#166]
I have been able to add tags to a list member using the method [update_list_member_tags](https://github.com/mailchimp/mailchimp-marketing-ruby/blob/master/lib/MailchimpMarketing/api/lists_api.rb#L871). But I haven't found a way of adding metadata to a member.
https://mailchimp.com/developer/transactional/docs/tags-metadata/

I was expecting the method `update_list_member_metadata` or something similar to exist.

What would be the best way of adding metadata to a member using this library?

**Comment by bipol-mc** [comment]
Hey @jfanals - 

[Tags metadata](https://mailchimp.com/developer/transactional/docs/tags-metadata/) is used for tagging in Mailchimp's  [Transactional](https://mailchimp.com/developer/transactional/) product api, where the [update_list_member_tags](https://mailchimp.com/developer/marketing/api/list-members/) is relevant to the [Mailchimp Marketing](https://mailchimp.com/developer/marketing/) product api.  We have a different SDK for the Transactional product [here](https://github.com/mailchimp/mailchimp-transactional-ruby/), which is why you were unable to find references to the metadata field in the Marketing SDK.

You can find a bit more information about how tagging is used in the Marketing API in our [Organize Contacts with Tags](https://mailchimp.com/developer/marketing/guides/organize-contacts-with-tags/) guide, however the metadata concept you linked from the Mailchimp Transactional guide won't apply to the Marketing side of things. 

Hope this helps - will leave this issue open for a bit if you have any further qs, but will close if this helps clear things up.

**Comment by jfanals** [comment]
Thank you for your quick reply.

So if I understand correctly I will not be able to add a metadata to a list member.
My idea was to include extra information (other than tags) to the list member so that we can pull that information in an email template.

I guess that is not possible to do, right?

**Comment by bipol-mc** [comment]
@jfanals I believe that one way to achieve this is with [merge fields](https://mailchimp.com/developer/marketing/api/list-merges/add-merge-field/) on the list, which could then be updated per each list member, and pulled into a template.

**Comment by jfanals** [comment]
Thank you, I am going to investigate that option :)
