### ISSUE TITLE
Body is a named parameter in the Ruby library

### ISSUE THREAD

**Issue by rjleaf** [mailchimp/mailchimp-client-lib-codegen#77]
Spec: Marketing, Section: list-member-tags

What was unclear / unexpected / confusing: Code example does not include usage for adding/removing tags.

Below is the current code example in the documentation for "Add or remove member tags":

```rb
require 'MailchimpMarketing'

begin
  client = MailchimpMarketing::Client.new
  client.set_config({ api_key: 'YOUR_API_KEY', server: 'YOUR_SERVER_PREFIX' })

  response = client.lists.update_list_member_tags('list_id', 'subscriber_hash')
  p response
rescue MailchimpMarketing::ApiError => e
  puts "Error: #{e}"
end
```

This is unclear because it does not show a developer how the body is passed. I assumed that the body parameter was just passed as an object at the end of the method call. Instead, the proper usage is:

```rb
require 'MailchimpMarketing'

begin
  client = MailchimpMarketing::Client.new
  client.set_config({ api_key: 'YOUR_API_KEY', server: 'YOUR_SERVER_PREFIX' })

  response = client.lists.update_list_member_tags('list_id', 'subscriber_hash', body: {
    tags: [{name: 'tag name', status: 'active'}]
  })
  p response
rescue MailchimpMarketing::ApiError => e
  puts "Error: #{e}"
end
```

Once I made this change, I was able to successfully assign / remove tags for a list member.

**Comment by bipol-mc** [comment]
Hey @rjleaf -

It seems like we had a bug around the expectations of body parameters for some of our functions, which we fixed in this PR https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/90

These functions should now have the body parameters as a required argument in the latest release.  There is still some work to be done in our code generation for rendering the code snippets correctly in the docs (the body is still shown as `{}`).  Closing this issue for now!
