### ISSUE TITLE
stats.total_contacts field missing from "Get List info" response 

### ISSUE THREAD

**Issue by vitoatsoundtoys** [mailchimp/mailchimp-client-lib-codegen#96]
[The API reference specifies](https://mailchimp.com/developer/marketing/api/lists/get-list-info/) that the response for a GET List call will return an object called "stats" that includes a property called "total_contacts", the total number of members on a list regardless of their subscription status. However in my experience, this field is missing from the response object.

**Comment by bipol-mc** [comment]
Hey there @vitoatsoundtoys  -- I looked into this and it seems like we are missing a required query parameter for this field: `?include_total_contacts=true`.  Adding this to your path should expose this field.

I'll be fixing the documentation to expose this URL parameter.  This specific field is guarded, since counting the members can be expensive for large lists, so it isn't a default field. 

Hope this helps!

**Comment by vitoatsoundtoys** [comment]
Hey @bipol-mc, thanks a ton for looking into this! This is great to know. I had found that I can also get the list size by calling the "List members info" endpoint (with count=0), which returns the "total_items" property. 

I don't think we'll be depending on knowing list sizes too much, but do you happen to know which method has less overhead?

**Comment by bipol-mc** [comment]
I believe the `stats` object on the top level list call will be more performant for larger lists, but with smaller list sizes the `total_items` should provide what you need, as you described.
